format = """
$directory\
$git_branch\
$git_status\
$python\
$rust\
$aws\
$line_break\
$character"""

[directory]
truncation_length = 3

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[aws]
format = '[$symbol($profile )(\($region\))]($style) '
symbol = " "

[python]
detect_extensions = []
python_binary = []

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
